# Generated by Django 4.2.7 on 2023-11-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ktalk', '0002_conversationtest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themetest',
            old_name='test',
            new_name='assistantrole',
        ),
    ]
